typedef struct tree
{
    int *T;   // Using Implicit Indexing of arrays to represent a BST...
    int size; // Max number of nodes the tree can bear...
    int length;
} Tree;

void init_bst(Tree *t, int n);
void insert_bst(Tree *t, int data);  // non-recursive insert...
void non_recursive_traverse(Tree t); // non-recursive inorder, preorder, postorder...
void inorder(Tree t);
void preorder(Tree t);
void postorder(Tree t);
void levelwise(Tree t); // to show levelwise nodes...
int isComplete(Tree t); // Check whether BST is a complete tree...
int levels(Tree t, int i);
int height(Tree t);